# Copyright (C) 2018 - 2021 Beckhoff Automation GmbH & Co. KG
# Customized Packet Filter - /etc/pf.conf

include "/etc/pf.conf.d/neoom.vars"

set skip on lo0
scrub in all

#table <neoom_mgmt_src> persist file "/etc/pf.tables/neoom_mgmt_src"
#table <neoom_xlat_allow> persist file "/etc/pf.tables/neoom_xlat_allow"

# ===== ADD load global vars & tables, visible to all anchors =====
#nat-anchor "neoom-nat"
#rdr-anchor "neoom-rdr"
#anchor neoom-global

# allow dynamic NAT configuration (e.g. luemuctl)
nat-anchor "bhf-nat/*"

# allow dynamic port forwarding configuration (e.g. luemuctl)
rdr-anchor "bhf-rdr/*"

# ===== ADD own dynamic NAT/RDR anchors; to load per-host rules =====
rdr-anchor "neoom-rdr"
load anchor "neoom-rdr" from "/etc/pf.conf.d/neoom-rdr"
nat-anchor "neoom-nat"
load anchor "neoom-nat" from "/etc/pf.conf.d/neoom-nat"

# ===== ADD early anchor for management/safety guardrails (evaluated first) =====
#anchor neoom-early
#load anchor neoom-early from "/etc/pf.conf.d/neoom-early"

# block all incoming and allow all outgoing traffic
#block return in all
#pass out quick all

# allow icmp6
#pass in quick proto icmp6 all

# allow icmp4 (ping)
#pass in quick inet proto icmp all icmp-type { echoreq, unreach }

# allow ssh
#pass in quick proto tcp to port ssh

# allow dynamic configuration for Beckhoff specific services
#anchor bhf
#load anchor bhf from "/etc/pf.conf.d/bhf"

# ===== ADD main anchor for gateway functionality =====
#anchor neoom
#load anchor neoom from "/etc/pf.conf.d/neoom"
