# common setting presets from Beckhoff
zfs_enable="YES"
dumpdev="AUTO"
ntpd_enable="YES"
pf_enable="YES"
pflog_enable="YES"
sshd_enable="YES"
sendmail_enable="NO"
sendmail_submit_enable="NO"
sendmail_outbound_enable="NO"
sendmail_msp_queue_enable="NO"
allscreens_kbdflags="-b quiet.off"
syslogd_flags="-ss"
devfs_system_ruleset="allow_usb_mount"

# Beckhoff/TwinCAT specific settings
runonce_enable="YES"
TcSystemService_enable="YES"
CXID_enable="YES"
MDPService_enable="YES"

# rename network interface name to printed names (visible in Device Manager)
ifconfig_igb0_name="X001"
ifconfig_igb1_name="X000"

# network settings
dhcpcd_enable="YES"
dhcpcd_flags="--clientid --hostname --waitip"
#ifconfig_DEFAULT="DHCP inet6 accept_rtadv"
#ifconfig_X000="inet 192.168.100.10 netmask 255.255.0.0 up"
#ifconfig_X001="inet 192.168.137.5 netmask 255.255.0.0 up"
#defaultrouter="192.168.100.1"

# enable routing
gateway_enable="YES"

# set host name (also possible in Device Manager)
hostname="BTN-000f5gof"

# activate German keyboard layout
keymap="de.kbd"

# activate routing for internal components (inverter, battery, ...)
neoom_routing_enable="YES"

