#
#  This file is read when going to multi-user and its contents piped thru
#  ``sysctl'' to adjust kernel values.  ``man 5 sysctl.conf'' for details.
#

# Uncomment this to prevent users from seeing information about processes that
# are being run under another UID.
#security.bsd.see_other_uids=0

# Compress application coredumps with zstd and put them in a central location
kern.compress_user_cores=2
kern.corefile=/var/coredumps/%N-%I.core

# disable keyboard shortcuts
kern.vt.kbd_debug=0
kern.vt.kbd_halt=0
kern.vt.kbd_panic=0
kern.vt.kbd_poweroff=0
kern.vt.kbd_reboot=0

# disable mwait idle loop optimization and set hlt as default
machdep.idle="spin"
machdep.idle_mwait=0

# IP option processing is expensive and has no practical use anymore
net.inet.ip.process_options=0

# Allow users from 'usb' group to mount usb memsticks
vfs.usermount=1
vfs.zfs.min_auto_ashift=12
kern.eventtimer.periodic="1"
kern.eventtimer.timer="HPET"
kern.timecounter.hardware="TSC"
machdep.intr_rt_bypass_enable="50"

# activate routing, requirement for gateways
net.inet.ip.forwarding=1

# no icmp-redirects to clients, today no longer used
net.inet.ip.redirect=1
# drop incoming redirects, today no longer used
net.inet.icmp.drop_redirect=1
# prohibit source-routing, old mechanism, no legit use-case today
net.inet.ip.sourceroute=0

# SYN to closed TCP ports -> no RST response, TCP stealth mode, =1 -> more diagnosis
net.inet.tcp.blackhole=2
# no "Port unreachable" an UDP icmp, UDP stealth mode
net.inet.udp.blackhole=1

# SYN flood protection
net.inet.tcp.syncookies=1
# randomize IP-ID
net.inet.ip.random_id=1 
#net.inet.ip.check_interface=1 
